### ISSUE TITLE
Player names and retainer names with special characters cause playback issues

### ISSUE THREAD

**Issue by jordguitar** [arcsidian/XivVoices#2]
If a character name has a special character, or a retainer name has a special character, playback breaks depending on what you have enabled and disabled. 

Example 1:
Player name is O'raha Tia. If the dialogue has the first part of the player name in the dialogue box (O'raha), ALL audio for that dialogue box is not played (as long as it had a file to play in the first place). This is prevalent in MSQ dialogue.

Example 2:
Retainer name is O'raha and Retainers playback is disabled in settings. The goodbye dialogue for the retainer is played when the retainer is dismissed. This does not affect retainers summoned after this.

**Comment by arcsidian** [comment]
Regarding Example 1:
This error has been fixed in a previous version, I just tested it by speaking to "A'aba Tia" and his dialogue had "Amaj'aa" in it, it worked just fine in file, and even when I removed the file and enabled Local TTS, there were no issues. If it still persists for you, please include dalamud log for that conversation to see what's happening (C:\Users\USER\AppData\Roaming\XIVLauncher)

Regarding Example 2:
This is most likely an error in the retainers json, that very sentence probably has a mismatch with the one in my list, I would like to know the race and gender if your retainer, so please talk to that retainer again and send me dalamug log,

**Comment by arcsidian** [comment]
Thank you for providing me with the logs, now I understand the issue more clearly, it's not the ' in the name, it's when the name ends with a ' without a follow-up letter, I just fixed it!

Also I added that mismatched sentence to the retainers list, so you won't face that problem anymore, I'll be pushing the update in a bit.
