### ISSUE TITLE
Suggestion for continuation of spoken speech dialogue.

### ISSUE THREAD

**Issue by Kronostorm** [arcsidian/XivVoices#8]
Would it be possible to add a function to press the confirm keybind button after said speech dialogue has completed. This way the dialogue can continue to the next speech without manual prompt from the user.

**Comment by arcsidian** [comment]
Thank you for your suggestion. Unfortunately, as explained in Discord a few weeks ago, this plugin has ceased further development due to personal reasons, everyone is welcome to fork it and continue its development themselves, or try a different plugin called [Artemis ](https://github.com/Sebane1/RoleplayingVoiceDalamud)which does a similar job to XIVV (but online instead of local) and it also has all of XIVV's files.
